datafiles:
  - id: client
    data_file_path: example_input_client.csv
    program_name: JCOIN
    hub_name: TEST
    variable_categories:
        - participant
        - demographic
    variable_transform_file_path: example_transforms_client.yaml
    outputted_tsv_file_dir: ''
  - id: client
    data_file_path: substance_use.csv
    program_name: JCOIN
    hub_name: TEST
    variable_categories:
        - follow_up
        - substance_use
    variable_transform_file_path: example_transforms_client.yaml
    outputted_tsv_file_dir: ''

replace_ids:
    id_file: "C:/Users/kranz-michael/projects/test-ids/test_submitter_ids.txt"
    map_file: "C:/Users/kranz-michael/projects/test-ids/id_store/id_mappings.csv"
    map_url: "C:/Users/kranz-michael/projects/test-ids-secrets.git"
    column: 'record_id'